### ISSUE TITLE
Bug: Use of "str.replace" is incorrect

### ISSUE THREAD

**Issue by phuang1024** [Skparab1/age-calculator#1]
Right now, in a few places, you are using `str.replace` like it modifies the string in place:
`my_str.replace("1", "2")`

However, the `replace` method returns a new string, so I think you meant to type
`my_str = my_str.replace("1", "2")`

I found this problem on lines 6 and 7.

**Comment by Skparab1** [comment]
Thanks!
Fixed now I think (yay)
